### ISSUE TITLE
For text labels, alignmentBaseline should instead be dominantBaseline

### ISSUE THREAD

**Issue by mjsarfatti** [plouc/nivo#254]
This happens for example here: https://github.com/plouc/nivo/blob/682cbed01babb4773568eb590463c22dfd0b5762/packages/nivo-bar/src/BarItem.js#L59

But I've seen it in other files as well.

"alignmentBaseline" is meant to be for elements children of `text`, see screenshot of [MDN pages](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/alignment-baseline?redirectlocale=en-US&redirectslug=SVG%2FAttribute%2Fdominant-baseline):

<img width="655" alt="screen shot 2018-07-30 at 18 50 03" src="https://user-images.githubusercontent.com/736316/43432809-8210b9d4-9429-11e8-9c8d-dfcd2468e993.png">

Moreover, I found that it works best with the value of "middle" instead of "center", at least in Chrome and Firefox.

I could do a PR but it's probably faster/easier for you since you know the code?

But let me know otherwise.

**Comment by mjsarfatti** [comment]
Ps: a fast CSS fix is the following:

```css
text {
  alignment-baseline: baseline !important; /* reset since Chrome wrongfully sees it as valid */
  dominant-baseline: middle;
}
```
