### ISSUE TITLE
Add support for biaxial charts

### ISSUE THREAD

**Issue by dep** [plouc/nivo#2666]
Continuation from https://github.com/plouc/nivo/issues/172

---

from @dragosdydy:

Hello,

I have looked around, i have checked the docs, I can't still figure out how to do a biaxial line chart. I have added the axisRight, but it is possible to use different key for that axis ?
I am looking for something that Left Axis is the line chart for 1 value and the Right Axis is a line for other type of value.

It is achievable with Nivo? I could show some examples if needed.
Thank you.

**Comment by dep** [comment]
I did want to share a working example fwiw:

```jsx
import React from "react";
import { ResponsiveLine } from "@nivo/line";
import { data, data2 } from "./data.js";
import "./DualYAxisChartExample.css";

const line1Color = "blue";

const getColoredAxis = (color) => {
  return {
    axis: {
      ticks: {
        line: {
          stroke: color,
        },
        text: { fill: color },
      },
      legend: {
        text: {
          fill: color,
        },
      },
    },
  };
};

const FirstYAxisChart = () => {
  return (
    <ResponsiveLine
      data={data}
      colors={[line1Color]}
      layers={["grid", "axes", "lines", "markers", "legends"]}
      axisLeft={{
        legend: "Points Scored",
        legendPosition: "middle",
        legendOffset: -40,
      }}
      theme={getColoredAxis(line1Color)}
      margin={{ top: 50, right: 50, bottom: 50, left: 50 }}
    />
  );
};

const SecondYAxisChart = () => {
  const data1And2 = data.concat(data2);

  return (
    <ResponsiveLine
      data={data1And2}
      colors={[
        "black",
        "red",
      ]} /* Make the first line transparent with 0 opacity */
      margin={{ top: 50, right: 50, bottom: 50, left: 50 }}
      axisRight={{
        legend: "Wins / Loss",
        legendPosition: "middle",
        legendOffset: 40,
      }}
      axisLeft={null}
      axisTop={null}
      enableGridY={false}
      axisBottom={null}
      theme={getColoredAxis("red")}
      /* Add this for tooltip */
      useMesh={true}
      enableSlices="x"
      sliceTooltip={({ slice }) => {
        return (
          <div
            style={{
              background: "white",
              padding: "9px 12px",
              border: "1px solid #ccc",
            }}
          >
            <div>x: {slice.points[0].data.x}</div>
            {slice.points.map((point) => (
              <div
                key={point.id}
                style={{
                  color:
                    point.serieColor === "black"
                      ? line1Color
                      : point.serieColor,
                  padding: "3px 0",
                }}
              >
                <strong>{point.serieId}</strong> [{point.data.yFormatted}]
              </div>
            ))}
          </div>
        );
      }}
    />
  );
};

function DualYAxisChartExample() {
  return (
    <div className="App">
      <h1>Two Y-Axis Line Chart</h1>
      <p>
        I'd like to have a chart with two lines on it. These would have
        different scales the first graph would have its y-axis displayed on the
        left and the second would have its y-axis displayed on the right
      </p>
      <div className="wrapper">
        <div className="graphContainer">
          <FirstYAxisChart />
        </div>
        <div className="secondGraph">
          <SecondYAxisChart />
        </div>
      </div>
    </div>
  );
}

export { DualYAxisChartExample };
```

`data.js`:
```js
export const data = [
  {
    "id": "line1",
    "color": "hsl(43, 70%, 50%)",
    "data": [
      {
        "x": "plane",
        "y": 197
      },
      {
        "x": "helicopter",
        "y": 108
      },
      {
        "x": "boat",
        "y": 99
      },
      {
        "x": "train",
        "y": 22
      },
      {
        "x": "subway",
        "y": 154
      },
      {
        "x": "bus",
        "y": 52
      },
      {
        "x": "car",
        "y": 142
      },
      {
        "x": "moto",
        "y": 107
      },
      {
        "x": "bicycle",
        "y": 202
      },
      {
        "x": "horse",
        "y": 38
      },
      {
        "x": "skateboard",
        "y": 90
      },
      {
        "x": "others",
        "y": 290
      }
    ]
  },
];

export const data2 = [
  {
    "id": "line2",
    "color": "hsl(43, 70%, 50%)",
    "data": [
      {
        "x": "plane",
        "y": 400
      },
      {
        "x": "helicopter",
        "y": 130
      },
      {
        "x": "boat",
        "y": 204
      },
      {
        "x": "train",
        "y": 40
      },
      {
        "x": "subway",
        "y": 20
      },
      {
        "x": "bus",
        "y": 30
      },
      {
        "x": "car",
        "y": 60
      },
      {
        "x": "moto",
        "y": 150
      },
      {
        "x": "bicycle",
        "y": 100
      },
      {
        "x": "horse",
        "y": 30
      },
      {
        "x": "skateboard",
        "y": 30
      },
      {
        "x": "others",
        "y": 30
      }
    ]
  },
];
```

and the css
```css
.App {
  font-family: sans-serif;
  text-align: center;
}

.wrapper {
  height: 300px;
  position: relative;
}
.graphContainer {
  height: 300px;
  position: absolute;
  top: 0px;
  width: 100%;
  z-index: 0;
}

.secondGraph {
  height: 300px;
  position: absolute;
  top: 0px;
  width: 100%;
  z-index: 4;
}

.App-logo {
  height: 40vmin;
  pointer-events: none;
}

@media (prefers-reduced-motion: no-preference) {
  .App-logo {
    animation: App-logo-spin infinite 20s linear;
  }
}

.App-header {
  background-color: #282c34;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  font-size: calc(10px + 2vmin);
  color: white;
}

.App-link {
  color: #61dafb;
}

@keyframes App-logo-spin {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}
```
